name: PIPOUMONEY
main: fr.pipoumoney.PipouMoney
version: 1.0.0
api-version: "1.20"
softdepend: [Vault, PlaceholderAPI]

commands:
  money:
    description: Main money command.
    usage: "/money help"
    aliases: [eco]
    permission: pipoumoney.use

  bal:
    description: Show your balance.
    usage: "/bal [player]"
    permission: pipoumoney.balance

  pay:
    description: Pay a player.
    usage: "/pay <player> <amount>"
    permission: pipoumoney.pay

  baltop:
    description: Show richest players.
    usage: "/baltop [n]"
    permission: pipoumoney.top

permissions:
  pipoumoney.use:
    description: Allows using /money.
    default: true

  pipoumoney.balance:
    description: Allows viewing your own balance.
    default: true

  pipoumoney.balance.other:
    description: Allows viewing other players' balance.
    default: op

  pipoumoney.pay:
    description: Allows paying other players.
    default: true

  pipoumoney.top:
    description: Allows using /baltop.
    default: true

  pipoumoney.settings:
    description: Allows opening /money settings.
    default: true

  pipoumoney.admin:
    description: Full admin access to PipouMoney.
    default: op
